# paths
train_image_path: /data/ephemeral/home/data/train/DCM
train_mask_path: /data/ephemeral/home/data/train/outputs_json
test_image_path: /data/ephemeral/home/data/test/DCM
hiera_path: /data/ephemeral/home/sam2_hiera_large.pt

# train
train_batch_size: 4
train_num_workers: 4

# valid
valid_batch_size: 2
valid_num_workers: 2
kfold: 5
k: -1
threshold: 0.5

# hyperparameter
lr: 0.001
max_epoch: 100

# optimizer
optimizer: adamw
optimizer_parameters:
  weight_decay: 0.01
  betas: [0.9, 0.999]

# scheduler
scheduler: cosineannealinglr
scheduler_parameters:
  # step: 40
  # gamma: 0.1

  # milestones: [10, 20]
  # gamma: 0.1
  
  T_max: 100
  eta_min: 0.00005
  
  # factor: 0.1
  # patience: 10


# random seed 
random_seed: 2024

# save
save_every: 10

# augmentation
image_size: 1024

# wandb
wandb_name: sam2unet_1024_100_hflip_colorjitter
wandb_id: 

# resume
resume: False
ckpt_path: ./checkpoints/
start_epoch: 0