# paths
train_image_path: /data/ephemeral/home/data_v2/train/DCM
train_mask_path: /data/ephemeral/home/data_v2/train/outputs_json
test_image_path: /data/ephemeral/home/data/test/DCM
hiera_path: /data/ephemeral/home/sam2_hiera_large.pt

# train
train_batch_size: 2
train_num_workers: 2

# valid
valid_batch_size: 2
valid_num_workers: 2
kfold: 5
k: 0
threshold: 0.5
valid_every: 2

# hyperparameter
lr: 2e-4
max_epoch: 40
smooth_factor: 0

# optimizer
optimizer: adamw
optimizer_parameters:
  weight_decay: 1e-6

# scheduler
scheduler: cosineannealinglr
scheduler_parameters:
  # steplr
  # step_size: 40
  # gamma: 0.1

  # multisteplr
  # milestones: [10, 20]
  # gamma: 0.1
  
  # cosineannealinglr
  T_max: 30
  eta_min: 1e-6
  
  # reducelronplateau
  # factor: 0.1
  # patience: 5


# random seed 
random_seed: 2024

# save
save_every: 5

# augmentation
image_size: 1024

# wandb
wandb_name: sam2unet_1024_best
wandb_id: 

# resume
resume: False
ckpt_path: ./checkpoints/
start_epoch: 0