# 데이터 및 모델 저장 경로
image_root: /data/ephemeral/home/data/train/DCM
label_root: /data/ephemeral/home/data/train/outputs_json
save_dir: /data/ephemeral/home/data/result

# 모델 라이브러리 및 사용 모델 정의
model_type: smp
model_name: UnetPlusPlus
encoder_name: tu-hrnet_w64
encoder_weights: imagenet
pretrained: True

# batch_size
train_batch_size: 2
valid_batch_size: 4

# hyperparameter
lr: 2e-4
weight_decay: 1e-6
train_num_workers: 8
valid_num_workers: 0
max_epoch: 50

# loss
loss:
    name: DiceBCELoss
    params: null

# optimizer
optim: Adam

# validation 인자
kfold: 0
val_every: 2
threshold: 0.5

# random seed
random_seed: 2024

# resize
size: 1024

# wandb
wandb_run_name: Test
wandb_run_id: None